---
name: Lint

on:
  push:
  pull_request:

jobs:
  app-lint:
    name: App linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run the Home Assistant app linter
        uses: frenck/action-app-linter@v2
        with:
          path: ./infinitude
